[project]
name = "pytorch-trainer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "brendanwood29", email = "brendanwwood22@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "omegaconf>=2.3.0",
    "torchinfo>=1.8.0",
    "tqdm>=4.67.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytorch-trainer",
]

[tool.uv.sources]
pytorch-trainer = { workspace = true }

[tool.uv.workspace]
members = [
    ".",
]

[project.optional-dependencies]
cpu = ["torch>=2.7"]
cuda = ["torch>=2.7"]  

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"        # or "single"
indent-style = "space"
docstring-code-format = true  # formats code blocks inside docstrings
[tool.ruff.lint]
select = ["E", "F", "I"]  # E=pycodestyle, F=pyflakes, I=isort
